### ISSUE TITLE
Custom output of filenames for minified files (compatible with file maps)

### ISSUE THREAD

**Issue by mkormendy** [tssajo/Minify#23]
I really love this for my home projects, but it's a bit of an issue for me to use at my work.

Unfortunately I am required to follow the naming conventions set by a team of developers before me, and I need to have different filenames for various minified files. Instead of having *.min.css / *.min.js as our production-ready files, we have *.max.css / *.max.js as our development files, and *.css / *.js as our final production-ready files.

It would be nice to have two options:

1. set the default minified output file suffix in sublime's User Settings for Minify.
2. set the minified output file suffix on a per file basis, but simply setting a comment in the development file (on any line in the file – meaning it can be set below the usual meta info found at the top of css or js files). For example:
```
/* minify-filename-suffix: ".suffix" */
/* minify-filename-prefix: "prefix-" */
```
(where ".suffix" is what is placed before the ending ".css" or ".js" extensions of the file. Obviously, "prefix" is prepended at the beginning of the file)

I'm not sure if this would automatically be compatible with css or js mapping by taking the development file's filename and putting that in the map file at the beginning, but I would think it allot for the change.

Thoughts?

**Comment by tssajo** [comment]
@mkormendy I understand that it is inconvenient to you that you must use your company's file naming conventions. But I do not think I will be changing how my Sublime Text plugin works just because of that.
It is pretty standard to just add the ".min" part to the file name right before the file extension for minified files and not the other way around (by removing ".max"). Also, I do not think it would be a good idea to parse into every file before minifying it to look for per file basis instructions. This would make my `Minify` plugin heavier and slower, and I prefer to have a light weight plugin.
However, please feel free to fork this project and implement yourself whatever features you may need. I am not against that at all.

**Comment by mkormendy** [comment]
Aww shucks, well thanks for your consideration.
