### ISSUE TITLE
svgo no tworking

### ISSUE THREAD

**Issue by fr-olivier** [tssajo/Minify#24]
Hello,

Node.js and svgo were already installed so I tried to minify a svg directly from ST, but nothing happens and I get this in the console (4 last lines only):
```
    p = subprocess.Popen(cmdToRun, stderr=subprocess.PIPE, shell=RUN_IN_SHELL)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'svgo'
```
What can I do to make it work?

Thank you,
François

**Comment by tssajo** [comment]
@fr-olivier What platform are you on? Windows? OSX? Linux?

Please open up a command prompt and issue the following command:
`svgo --version`

What do you get?

If you issue this command:
`which svgo`
What do you get?

Please let me know!

**Comment by tssajo** [comment]
I can give you some more info:

First of all, I just released a new version of the `Minify` package today, because a few days ago I discovered a bug which prevented SVG file minification to work at least on Windows. I don't think other platforms were affected by this bug. But still, I recommend you to upgrade to `Minify` v1.1.4 (if you installed my `Minify` plugin via Package Control then Package Control will automatically upgrade it).

Second, from your error message it seems that the `svgo` command was not found, this could be of an indication of a Mac OS X issue, and the solution for that is outlined here: https://github.com/tssajo/Minify#important-note-for-mac-os-x-users

So I'm not sure which platform you are on (it seems to me that you are possibly on a Mac), but I suggest you to upgrade to the latest version of `Minify` plugin regardless of your platform.

I'm closing this issue now. But If I hear from you and you'll be saying that my suggested solutions did not work then I will gladly help you. Just let me know, okay? Thanks!

**Comment by tssajo** [comment]
@fr-olivier I just release v1.1.5 of `Minify` plugin for ST. It fixes PATH related issues on Mac OS X. So if you are on that platform then please upgrade `Minify` to v1.1.5 and I am quiet certain that it will work this time for you too.

**Comment by fr-olivier** [comment]
Hello tssajo,
Thanks a lot for your support. I installed ```Minify``` v1.1.4 on my personal Mac and after applying the PATH workaround, it works fine. I didn't upgrade it to v1.1.5 yet so I don't know if it'll still work.
But back on my professional iMac, I upgraded to v1.1.5 and it doesn't work: when I run the Minify command, I get a ```PermissionError: [Errno 13] Permission denied``` error.
If I remove the PATH workaround (eg deleting the symlink to usr/local/lib/node_modules/svgo which was in usr/local/bin), I get a ```FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/svgo'``` error.

**Comment by tssajo** [comment]
@fr-olivier I'm glad to hear that `Minify` works fine on one of the computers you use.
I can help you make it work on the other one too. Please do the following:
Open up Terminal and run the following commands:
`sudo chown -R $USER /usr/local` (note: you need to enter your password to run this command)
then run these ones:
`rm /usr/bin/node`
`rm /usr/local/bin/svgo`
`exit` (you can close the Terminal window now)
At this point you might need to reinstall the latest version of Node.js: Just visit https://nodejs.org/ and click on the green INSTALL button and install the downloaded program.
After a successful node re-installation please open Terminal again and run the following commands:
`npm install -g clean-css uglifycss js-beautify html-minifier uglify-js svgo`
`npm update -g clean-css uglifycss js-beautify html-minifier uglify-js svgo`
(The `-g` switch is important in the above command!)
Now when you run this:
`which svgo`
then you should see:
`/usr/local/bin/svgo`
you can do this too:
`svgo --version`
and you should see a version number.
You can close the Terminal window now and launch your Sublime Text editor. `Minify` should work fine now.
Please let me know if this worked or not. Note: If you get any error messages at any point then please send those to me! Thanks!

**Comment by fr-olivier** [comment]
Should I really reinstall Node? I had bad reinstall experiences in the past
and as I use it for other processes, so I can't afford to break it. Except
if you can help me if that happens :)

**Comment by tssajo** [comment]
You may not need to reinstall Node. In that case just skip that step!

**Comment by fr-olivier** [comment]
I followed your steps without reinstalling Node and now ```Minify``` works exactly as expected. Thanks a lot, it's really great to have such a fast support.

**Comment by tssajo** [comment]
And I'm glad that I was able to help. Thanks for reporting the issue at the first place.
