### ISSUE TITLE
how to minify the file but not in a new file?

### ISSUE THREAD

**Issue by ioriandy4** [tssajo/Minify#37]
for example , I want to minify the file index.js, but the plugins will minify it by creating a new file index.min.js and index.js don't change.  I want index.js change and not creating index.min.js. How to do?

**Comment by tssajo** [comment]
@ioriandy4 This `Minify` package cannot minify to the same file. It creates a new file on purpose, so you'll still have the original file untouched.

The solution I suggest is this: `Minify` can be configured to auto-minify on save. With that setting enabled, every time you save index.js it will always (re)create the minified index.min.js file automatically. With this setup you can change your HTML file(s) to always load index.min.js instead of index.js  I hope this will be acceptable for your use case.

**Comment by ioriandy4** [comment]
Can it set to minify to the same file on  Later versions ?

**Comment by tssajo** [comment]
@ioriandy4 I don't think that I'll ever add "minifying to the same file" as a feature. Why? Because it would be a very dangerous operation if it would overwrite your original file. Minifying is a non-reversible operation. For example, you would lose all your comments and original variable names, etc. in your program code. I do not want to implement a dangerous feature. IMO, it is always much safer to minify to a different file. Note: If you really want then you can rename your index.min.js file to index.js (overwriting the original index.js) manually.
