### ISSUE TITLE
In Sublime Text 3 using trying to minify a javascript file doesn't work

### ISSUE THREAD

**Issue by gespinha** [tssajo/Minify#4]
I am using Sublime Text 3 and when I try to minify a javascript file, it doesn't work. Nothing happens.

Is this odd for you?

**Comment by mike-anthony** [comment]
Hi all, just continuing here instead of opening a new issue.

I'm running a classic Windows/XAMPP setup. I have Node installed (also direct installer), as well as UglifyJS, which works in the command prompt as well as MinGW. Unfortunately, it stops at `cmdToRun`.

Now, I know I had this problem before, but I don't remember what I did to fix it.

Sublime is running as Administrator as well.

The only notable thing that seems out of the ordinary is this:

    $ uglifyjs --version
    util.puts: Use console.log instead
    uglify-js 2.4.19

Anyone have an idea what's wrong here?

**Comment by mike-anthony** [comment]
Ah, figured it out. Had to use this command:

    C:\\Users\\<user>\\AppData\\Roaming\\npm\\uglifyjs.cmd

**Comment by Bruskyer** [comment]
Minify for Sublime Text 3 is not working on windows
![2019-10-07_14-38-35](https://user-images.githubusercontent.com/32862706/66308622-3cc80200-e910-11e9-9f20-428dae8bdc0e.jpg)
also node is installed, pls can you share configuration for win

**Comment by tssajo** [comment]
@Bruskyer Please follow step 2 and step 3 of the installation instructions!

2. Install Node.js
3. Install required Node.js CLI apps:
`npm install -g clean-css-cli uglifycss js-beautify html-minifier uglify-js minjson svgo`

**Comment by Bruskyer** [comment]
Thanks alot now its working

**Comment by Bruskyer** [comment]
> Thanks a lot now its working
> 
> @Bruskyer Please follow step 2 and step 3 of the installation instructions!
> 
>     1. Install Node.js
> 
>     2. Install required Node.js CLI apps:
>        `npm install -g clean-css-cli uglifycss js-beautify html-minifier uglify-js minjson svgo`
