### ISSUE TITLE
feature request: uglify-js_options

### ISSUE THREAD

**Issue by paponius** [tssajo/Minify#47]
hi, maybe I just can't find it,
I would like an option to:
{
	"uglify-js_options": "-c drop_console=true"
}
although there already is -c
but anyways there is nothing like uglify-js_options, I tried all sensible possibilities. Is it there hiding somewhere?
I made a custom uglifyjs.cmd, adding the option from there, but I just don't like it that way

**Comment by tssajo** [comment]
@paponius Thank you for noticing the missing `uglify-js_options` from the settings file (and from the python script). I added the requested feature, it is available from version 1.2.6 and above.

In your case, because `-c` is already added by the `Minify` plugin, you only need to add the rest to the `uglify-js_options` setting, like this:

```
"uglifyjs_options": "drop_console=true",
```
