### ISSUE TITLE
Sublime 3 Minify error.

### ISSUE THREAD

**Issue by alexrada** [tssajo/Minify#69]
When doing minify, the following errors occur. I need to restart sublime and it works.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1070, in run_
    edit = self.view.begin_edit(edit_token, self.name())
TypeError: 'str' object is not callable
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1070, in run_
    edit = self.view.begin_edit(edit_token, self.name())
TypeError: 'str' object is not callable

**Comment by tssajo** [comment]
This is really weird. Especially that it starts to work after restarting the SublimeText editor.

The error message indicates that the error occurs in the file `/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py` this file is not part of the Minify plugin, it is part of the SublimeText editor! Maybe try to re-download and reinstall your SublimeText editor, I suggest you install the latest stable version. Other than this, I cannot do too much about it because this seems to be a problem with your SublimeText editor itself or with your Mac. You see, many people use the Minify plugin for SublimeText on Macs and noone else reported an issue like this. I leave this Issue open for a while to see if anyone else is joining in with the same problem. But if not then it is very likely that you are the only one who had this problem and that is indicating that something must be wrong with your SublimeText installation on your end.
