### ISSUE TITLE
Wrong minify css font

### ISSUE THREAD

**Issue by aaburlaka** [tssajo/Minify#83]
I have css code:
`.welcome_wrapper p {
	font: 300 20px/30px 'Open Sans';
	color: #fff;
}
`
and after minify get:
`.welcome_wrapper p{color:#fff}`

Why it goes wrong?

**Comment by tssajo** [comment]
@aaburlaka I don't know.
Maybe the syntax of the font property is invalid in your example?
Please check the proper syntax e.g. here:
https://www.w3schools.com/cssref/pr_font_font.asp
If you believe that the syntax is correct and there is a bug in CSS minifier then please report the issue here:
https://github.com/jakubpawlowicz/clean-css
We use clean-css for CSS minification.
Thanks!
